# Generated by Django 2.2.2 on 2019-11-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='parent_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='updates.Update'),
        ),
        migrations.AlterField(
            model_name='update',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
